name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node: ['20']
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm run test
        env:
          HPKV_API_BASE_URL: ${{ secrets.HPKV_API_BASE_URL }}
          HPKV_API_KEY: ${{ secrets.HPKV_API_KEY }}

  compatibility:
    name: Test package compatibility
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Test CommonJS import
        run: |
          echo "const { multiplayer } = require('./dist/index.js');" > test-cjs.js
          echo "console.log('CommonJS import:', typeof multiplayer);" >> test-cjs.js
          node test-cjs.js

      - name: Test ES Module import
        run: |
          echo '{"type": "module"}' > test-package.json
          echo "import { multiplayer } from './dist/index.mjs';" > test-esm.mjs
          echo "console.log('ES Module import:', typeof multiplayer);" >> test-esm.mjs
          node test-esm.mjs

      - name: Cleanup
        run: rm -f test-cjs.js test-esm.mjs test-package.json 