name: Release

on:
  release:
    types: [created]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build
        env:
          HPKV_API_BASE_URL: ${{ secrets.HPKV_API_BASE_URL }}
          HPKV_API_KEY: ${{ secrets.HPKV_API_KEY }}
          NEXT_PUBLIC_HPKV_API_BASE_URL: ${{ secrets.HPKV_API_BASE_URL }}

      - name: Run tests
        run: pnpm test
        env:
          HPKV_API_BASE_URL: ${{ secrets.HPKV_API_BASE_URL }}
          HPKV_API_KEY: ${{ secrets.HPKV_API_KEY }}

      - name: Publish packages
        run: pnpm changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Send a notification
        run: |
          echo "Published @hpkv/zustand-multiplayer version ${{ github.event.release.tag_name }}"
          echo "Release notes: ${{ github.event.release.html_url }}"